export const SITE_URL = 'https://www.truckerlifeai.com'
export const SITE_NAME = 'Trucker Life AI'
export const APP_STORE_URL = 'https://apps.apple.com/us/app/trucker-life-ai/id6769266788'
export const APP_STORE_ID = '6769266788'
export const PRIVACY_URL = 'https://www.truckerlifeai.com/privacy'
export const TERMS_URL = 'https://www.truckerlifeai.com/terms'
export const LEGAL_URL = 'https://www.truckerlifeai.com/legal/'
export const OG_IMAGE_URL = 'https://www.truckerlifeai.com/og-image.png'
export const LOGO_URL = 'https://www.truckerlifeai.com/apple-touch-icon.png'
export const DEFAULT_DESCRIPTION =
  'The AI co-driver for owner-operators. Track loads, fuel, deadhead, IFTA, and true profit per mile from the cab.'
export const FOUNDER_NAME = 'Sarpreet Singh'
